<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <TargetFramework>net472</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <OutputPath>..\..\..\Compat\1.6\SupplyChain\Assemblies</OutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <BaseOutputPath>..\..\..\Compat\1.6\SupplyChain\Assemblies</BaseOutputPath>
        <Configurations>Debug;Release;Testing</Configurations>
        <PlatformTarget>x64</PlatformTarget>
        <AssemblyName>Empire.Specialists.SC</AssemblyName>
        <RootNamespace>FactionColonies.Specialists.SC</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <!-- Rimworld -->
        <Reference Condition="'$(Configuration)' == 'Debug'" Include="../../../RimWorldWin64_Data/*.dll">
            <Private>False</Private>
        </Reference>
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <!-- Empire base mod -->
        <Reference Include="Empire">
            <HintPath>..\..\..\..\Empire\1.6\Assemblies\Empire.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <!-- Empire Specialists main assembly -->
        <Reference Include="Empire.Specialists">
            <HintPath>..\..\Assemblies\Empire.Specialists.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <!-- Empire Supply Chain -->
        <Reference Include="Empire.SupplyChain">
            <HintPath>..\..\..\..\Empire-SupplyChain\1.6\Assemblies\Empire.SupplyChain.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Reference Update="mscorlib">
            <Private>False</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Reference Update="System">
            <Private>False</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Reference Update="System.Core">
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
